<!DOCTYPE HTML>
<html lang="de">
<head>
<title>Try - Syntax &amp; Verwendung | AutoHotkey v1</title>
<meta name="description" content="Die Try-Anweisung schützt eine oder mehrere Anweisungen vor Laufzeitfehlern und via Throw ausgelöste Ausnahmen." />
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="../static/theme.css" rel="stylesheet" type="text/css" />
<script src="../static/content.js" type="text/javascript"></script>
<script src="../static/ga4.js" type="text/javascript"></script>
</head>
<body>

<h1>Try <span class="ver">[v1.1.04+]</span></h1>

<p>Schützt eine oder mehrere <a href="../Concepts.htm#statement">Anweisungen</a> vor Laufzeitfehlern und via <a href="Throw.htm">Throw</a> ausgelöste Ausnahmen.</p>

<pre class="Syntax"><span class="func">Try</span> <i>Anweisung</i></pre>
<pre class="Syntax" style="line-height: 100%">
<span class="func">Try</span>
{
    <i>Anweisungen</i>
}
</pre>
<h2 id="Remarks">Bemerkungen</h2>
<p>Nach einem <em>Try</em> erfolgt üblicherweise ein <a href="Block.htm">Block</a> (eine oder mehrere <a href="../Concepts.htm#statement">Anweisungen</a>, die von geschweiften Klammern umschlossen sind). Wenn nur eine einzige Anweisung verwendet wird, kann diese direkt neben <em>Try</em> gesetzt werden, oder darunter ohne geschweifte Klammern. Um Code anzugeben, der nur ausgeführt wird, wenn <em>Try</em> einen Fehler abfängt, verwenden Sie <a href="Catch.htm">Catch</a>.</p>
<p>Eine Ausnahme kann entweder mit <a href="Throw.htm">Throw</a> oder durch das Programm beim Auftreten eines Laufzeitfehlers ausgelöst werden. Wenn eine Ausnahme innerhalb eines <em>Try</em>-Blocks oder einer Funktion, die von einem solchen Block aufgerufen wird, ausgelöst wird, geschieht Folgendes:</p>
<ul>
  <li>Wenn ein zugehöriges <a href="Catch.htm">Catch</a> vorhanden ist, wird die Ausführung dort fortgesetzt.</li>
  <li>Wenn kein <em>Catch</em>, aber ein <a href="Finally.htm">Finally</a> vorhanden ist, wird dieses ausgeführt, aber danach wird die Ausnahme automatisch erneut ausgelöst.</li>
  <li>Wenn weder ein <em>Catch</em> noch ein <em>Finally</em> vorhanden ist, wird die Ausführung bei der nächsten Zeile außerhalb des <em>Try</em>-Blocks fortgesetzt.</li>
</ul>
<p>Wenn eine Ausnahme ausgelöst wird, während keine <em>Try</em>-Blöcke ausgeführt werden, wird eine Fehlermeldung angezeigt und der aktuelle Thread beendet.</p>
<p>Je nach Bedarf kann der <a href="Block.htm#otb">One True Brace (OTB) Style</a> bei einem <em>Try</em> verwendet werden. Zum Beispiel:</p>
<pre>try {
    ...
} catch e {
    ...
}</pre>

<h2 id="Related">Siehe auch</h2>
<p><a href="Catch.htm">Catch</a>, <a href="Throw.htm">Throw</a>, <a href="Finally.htm">Finally</a>, <a href="Block.htm">Blöcke</a>, <a href="OnError.htm">OnError()</a></p>

<h2 id="Examples">Beispiele</h2>
<div class="ex" id="ex_basic">
<p><a class="ex_number" href="#ex_basic"></a> Zeigt das Grundkonzept von <em>Try-Catch</em> und <em>Throw</em>.</p>
<pre>try  <em>; Versucht den Code auszuführen.</em>
{
    HalloWelt()
    MacheToast()
}
<a href="Catch.htm">catch</a> e  <em>; Behandelt den ersten Fehler, ausgelöst durch den vorherigen Block.</em>
{
    MsgBox, Eine Ausnahme wurde ausgelöst!`nSpeziell: %e%
    <a href="Exit.htm">Exit</a>
}

HalloWelt()  <em>; Ist immer erfolgreich.</em>
{
    MsgBox, Hallo, Welt!
}

MacheToast()  <em>; Schlägt immer fehl.</em>
{
    <em>; Sofort zur Fehlerbehandlung des Try-Blocks springen:</em>
    <a href="Throw.htm">throw</a> A_ThisFunc " ist nicht implementiert, sorry"
}
</pre>
</div>

<div class="ex" id="ex_el">
<p><a class="ex_number" href="#ex_el"></a> Zeigt die Verwendung von <em>Try-Catch</em> anstelle von <a href="../misc/ErrorLevel.htm">ErrorLevel</a>.</p>
<pre>try
{
    <em>; Nachfolgend wird versucht, bestimmte Dateitypen zu sichern:</em>
    FileCopy, %A_MyDocuments%\*.txt, D:\Backup\Textdokumente
    FileCopy, %A_MyDocuments%\*.doc, D:\Backup\Textdokumente
    FileCopy, %A_MyDocuments%\*.jpg, D:\Backup\Fotos
}
catch
{
    MsgBox, 16,, Beim Sichern der Dateien ist ein Fehler aufgetreten!
    ExitApp
}
</pre>
</div>

<div class="ex" id="ex_com">
<p><a class="ex_number" href="#ex_com"></a> Zeigt die Verwendung von <em>Try-Catch</em> bei COM-Fehlern. Einzelheiten über das hier verwendete COM-Objekt finden Sie unter <a href="https://learn.microsoft.com/previous-versions/visualstudio/visual-studio-6.0/aa227633(v=vs.60)">Using the ScriptControl (Microsoft Docs)</a>.</p>
<pre>try
{
    obj := <a href="ComObjCreate.htm">ComObjCreate</a>("ScriptControl")
    obj.ExecuteStatement("MsgBox ""Dies ist ein eingebettetes VBScript""")
    obj.InvalidMethod() <em>; Diese Zeile erzeugt einen Laufzeitfehler.</em>
}
catch e
{
    <em>; Um mehr über das in e enthaltene Objekt zu erfahren, siehe <a href="Throw.htm#Exception">Exception()</a>.</em>
    MsgBox, 16,, % "Ausnahme ausgelöst!`n`nWas: " e.what "`nDatei: " e.file
        . "`nZeile: " e.line "`nNachricht: " e.message "`nZusatz: " e.extra
}
</pre>
</div>

<div class="ex" id="ex_nesting">
<p><a class="ex_number" href="#ex_nesting"></a> Zeigt verschachtelte <em>Try-Catch</em>-Anweisungen.</p>
<pre>try Beispiel1() <em>; Einzelanweisungen können neben dem Try stehen.</em>
catch e
    MsgBox, Beispiel1() hat "%e%" ausgelöst.

Beispiel1()
{
    try Beispiel2()
    catch e
    {
        if (e = 1)
            throw e <em>; Ausnahme erneut auslösen, damit der Aufrufer sie abfangen kann.</em>
        else
            MsgBox, Beispiel2() hat "%e%" ausgelöst.
    }
}

Beispiel2()
{
    Random, o, 1, 2
    throw o
}</pre>
</div>

</body>
</html>
