<!DOCTYPE HTML>
<html lang="de">
<head>
<title>Try - Syntax &amp; Verwendung | AutoHotkey</title>
<meta name="description" content="Die Try-Anweisung schützt eine oder mehrere Codezeilen vor Laufzeitfehlern und Ausnahmen, die von der Throw-Anweisung ausgelöst werden." />
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="../static/theme.css" rel="stylesheet" type="text/css" />
<script src="../static/content.js" type="text/javascript"></script>
<script src="../static/ga4.js" type="text/javascript"></script>
</head>
<body>

<h1>Try <span class="ver">[v1.1.04+]</span></h1>

<p>Schützt eine oder mehrere Anweisungen (Befehle oder Ausdrücke) vor Laufzeitfehlern und Ausnahmen, die vom <a href="Throw.htm">Throw</a>-Befehl ausgelöst werden.</p>

<pre class="Syntax"><span class="func">Try</span> <i>Anweisung</i></pre>
<pre class="Syntax" style="line-height: 100%">
<span class="func">Try</span>
{
    <i>Anweisungen</i>
}
</pre>
<h2 id="Remarks">Bemerkungen</h2>
<p>Nach einem <em>Try</em> erfolgt üblicherweise ein <a href="Block.htm">Block</a> - das sind eine oder mehrere Anweisungen (Befehle oder Ausdrücke), die von geschweiften Klammern umschlossen sind. Verwendet man nur eine Anweisung, kann sie direkt neben <em>Try</em> gesetzt werden, oder darunter ohne geschweifte Klammern. Der <a href="Catch.htm">Catch</a>-Befehl kann genutzt werden, um Zeilen auszuführen, wenn <em>Try</em> einen Fehler erfasst.</p>
<p>Eine Ausnahme kann ausgelöst werden, wenn der <a href="Throw.htm">throw</a>-Befehl verwendet wird oder wenn das Programm einen Laufzeitfehler verursachen sollte. Wenn eine Ausnahme vom Inneren eines Try-Blocks ausgelöst oder wenn eine Funktion von so einem aufgerufen wird, passiert folgendes:</p>
<ul>
  <li>Gibt es eine entsprechende <a href="Catch.htm">catch</a>-Anweisung, wird die Ausführung dort fortgesetzt.</li>
  <li>Wenn anstelle der catch-Anweisung nur eine <a href="Finally.htm">finally</a>-Anweisung vorhanden ist, wird sie ausgeführt, bis sie ihr Ende erreicht hat, danach wird die Ausnahme wieder automatisch ausgelöst.</li>
  <li>Gibt es weder eine catch-Anweisung noch eine finally-Anweisung, wird die Ausführung bei der nächsten Zeile außerhalb des try-Blocks fortgesetzt.</li>
</ul>
<p>Laufen beim Auslösen einer Ausnahme gerade keine try-Blocks, wird eine Fehlermeldung angezeigt und der aktuelle Thread beendet.</p>
<p>Bei Bedarf kann der "<a href="Block.htm#otb">One True Brace Style</a>" beim <em>Try</em>-Befehl angewendet werden. Zum Beispiel:</p>
<pre>try {
    ...
} catch e {
    ...
}</pre>

<h2 id="Related">Siehe auch</h2>
<p><a href="Catch.htm">Catch</a>, <a href="Throw.htm">Throw</a>, <a href="Finally.htm">Finally</a>, <a href="Block.htm">Blöcke</a>, <a href="OnError.htm">OnError()</a></p>

<h2 id="Examples">Beispiele</h2>
<div class="ex" id="ex_basic">
<p><a class="ex_number" href="#ex_basic"></a> Demonstriert das Grundkonzept von try/catch/throw.</p>
<pre>try  <em>; Versucht, den Code auszuführen.</em>
{
    HalloWelt()
    MacheToast()
}
<a href="Catch.htm">catch</a> e  <em>; Verarbeitet den ersten Fehler/Ausnahme, ausgelöst durch den vorherigen Block.</em>
{
    MsgBox, Eine Ausnahme wurde ausgelöst!`nSpeziell: %e%
    <a href="Exit.htm">Exit</a>
}

HalloWelt()  <em>; Ist immer erfolgreich.</em>
{
    MsgBox, Hallo, Welt!
}

MacheToast()  <em>; Schlägt immer fehl.</em>
{
    <em>; Springt sofort zur Fehlerbehandlung des Try-Blocks:</em>
    <a href="Throw.htm">throw</a> A_ThisFunc " ist nicht implementiert, sorry"
}
</pre>
</div>

<div class="ex" id="ex_el">
<p><a class="ex_number" href="#ex_el"></a> Demonstriert die Verwendung von try/catch anstelle von ErrorLevel.</p>
<pre>try
{
    <em>; Nachfolgend wird versucht, bestimmte Dateitypen abzusichern:</em>
    FileCopy, %A_MyDocuments%\*.txt, D:\Backup\Textdokumente
    FileCopy, %A_MyDocuments%\*.doc, D:\Backup\Textdokumente
    FileCopy, %A_MyDocuments%\*.jpg, D:\Backup\Fotos
}
catch
{
    MsgBox, 16,, Es trat ein Fehler beim Absichern der Dateien auf!
    ExitApp
}
</pre>
</div>

<div class="ex" id="ex_com">
<p><a class="ex_number" href="#ex_com"></a> Demonstriert die Verwendung von try/catch im Umgang mit COM-Fehlern. Einzelheiten über das hier verwendete COM-Objekt finden Sie unter <a href="https://learn.microsoft.com/previous-versions/visualstudio/visual-studio-6.0/aa227633(v=vs.60)">Using the ScriptControl (Microsoft Docs)</a>.</p>
<pre>try
{
    obj := <a href="ComObjCreate.htm">ComObjCreate</a>("ScriptControl")
    obj.ExecuteStatement("MsgBox ""Das ist ein eingebettetes VBScript""")
    obj.InvalidMethod() <em>; Diese Zeile erzeugt einen Laufzeitfehler.</em>
}
catch e
{
    <em>; Um mehr über das Objekt zu erfahren, das in e enthalten ist, siehe <a href="Throw.htm#Exception">Exception()</a>.</em>
    MsgBox, 16,, % "Ausnahme ausgelöst!`n`nWas: " e.what "`nDatei: " e.file
        . "`nZeile: " e.line "`nNachricht: " e.message "`nZusatz: " e.extra
}
</pre>
</div>

<div class="ex" id="ex_nesting">
<p><a class="ex_number" href="#ex_nesting"></a> Demonstriert verschachtelte Try-Catch-Anweisungen.</p>
<pre>try Beispiel1() <em>; Jede Einzelanweisung kann auf derselben Zeile des Try-Befehls stehen.</em>
catch e
    MsgBox, Beispiel1() hat "%e%" ausgelöst.

Beispiel1()
{
    try Beispiel2()
    catch e
    {
        if (e = 1)
            throw e <em>; Ausnahme wird nochmals ausgelöst, so dass der Aufrufer sie abfangen kann.</em>
        else
            MsgBox, Beispiel2() hat "%e%" ausgelöst.
    }
}

Beispiel2()
{
    Random, o, 1, 2
    throw o
}</pre>
</div>

</body>
</html>
